#!/usr/bin/env python3
"""
Multi-Provider Email Delivery System
Supports: Gmail SMTP, Mailgun, Brevo (Sendinblue), Resend
All have free tiers!
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from logger import get_logger

logger = get_logger(__name__)


# ============================================================================
# OPTION 1: Gmail SMTP (EASIEST - No API key, just use your Gmail!)
# ============================================================================

def send_via_gmail_smtp(video_path: str, instructions_path: str = None):
    """
    Send via Gmail SMTP - EASIEST option!
    
    Setup:
    1. Go to Google Account Settings
    2. Enable 2-Factor Authentication
    3. Generate App Password: https://myaccount.google.com/apppasswords
    4. Use that 16-character password (not your regular Gmail password)
    
    Environment Variables:
    - GMAIL_ADDRESS: your-email@gmail.com
    - GMAIL_APP_PASSWORD: your 16-char app password (no spaces)
    """
    try:
        gmail_address = os.getenv('GMAIL_ADDRESS')
        gmail_password = os.getenv('GMAIL_APP_PASSWORD')
        recipient = os.getenv('RECIPIENT_EMAIL') or gmail_address
        
        if not gmail_address or not gmail_password:
            logger.error("Gmail credentials not set. Need: GMAIL_ADDRESS, GMAIL_APP_PASSWORD")
            return False
        
        logger.info(f"📧 Sending via Gmail to {recipient}...")
        
        # Create message
        msg = MIMEMultipart()
        msg['From'] = gmail_address
        msg['To'] = recipient
        msg['Subject'] = f'🎥 YouTube Video Ready: {os.path.basename(video_path)}'
        
        # Email body
        video_size = os.path.getsize(video_path) / (1024 * 1024)
        body = f"""
Your YouTube video is ready!

📹 Video: {os.path.basename(video_path)}
💾 Size: {video_size:.1f}MB
🎬 Format: 720p HD MP4

Next Steps:
1. Download the attached video
2. Review the content
3. Upload to YouTube

Generated by your Free YouTube Agent on Render
"""
        msg.attach(MIMEText(body, 'plain'))
        
        # Attach video
        logger.info(f"Attaching video ({video_size:.1f}MB)...")
        with open(video_path, 'rb') as f:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header('Content-Disposition', f'attachment; filename={os.path.basename(video_path)}')
            msg.attach(part)
        
        # Attach instructions if provided
        if instructions_path and os.path.exists(instructions_path):
            logger.info("Attaching instructions...")
            with open(instructions_path, 'rb') as f:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header('Content-Disposition', f'attachment; filename={os.path.basename(instructions_path)}')
                msg.attach(part)
        
        # Send via Gmail SMTP
        logger.info("Connecting to Gmail SMTP...")
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(gmail_address, gmail_password)
        server.send_message(msg)
        server.quit()
        
        logger.info(f"✅ Email sent successfully via Gmail!")
        return True
        
    except Exception as e:
        logger.error(f"Gmail SMTP error: {e}")
        import traceback
        logger.error(traceback.format_exc())
        return False


# ============================================================================
# MASTER FUNCTION - This is what main_free.py imports!
# ============================================================================

def send_video_email(video_path: str, instructions_path: str = None):
    """
    Main function to send video via email
    This is imported by main_free.py
    
    Currently only supports Gmail SMTP (easiest option)
    Returns True if email sent successfully, False otherwise
    """
    logger.info("📧 Attempting to send video via email...")
    
    # Try Gmail SMTP
    if os.getenv('GMAIL_ADDRESS'):
        logger.info("Using Gmail SMTP...")
        return send_via_gmail_smtp(video_path, instructions_path)
    else:
        logger.error("No email service configured!")
        logger.error("Set GMAIL_ADDRESS and GMAIL_APP_PASSWORD environment variables")
        return False


if __name__ == "__main__":
    print("Email delivery module loaded")
    print("\nTo use Gmail SMTP:")
    print("1. Set GMAIL_ADDRESS environment variable")
    print("2. Set GMAIL_APP_PASSWORD environment variable")
    print("3. Set RECIPIENT_EMAIL environment variable (optional)")
    print("4. Set OUTPUT_DELIVERY=email")